export const flavorLabels: Record<string, string> = {
  sweet: '甜甜的（桃桃果、豆子）',
  sour: '酸酸的（番茄、利木果）',
  spicy: '辣辣的（成熟的紅蘿蔔）',
  bitter: '苦苦的（馬鈴薯、莓莓果、海藻）',
  astringent: '澀澀的（小麥、零餘果）',
}

export const environmentLabels: Record<string, string> = {
  bright: '明亮',
  warm: '溫暖',
  moist: '滋潤',
  dry: '乾燥',
  dim: '昏暗',
  cool: '涼爽',
}

export const thingLabels: Record<string, string> = {
  nature: '能感受大自然的',
  soft: '柔軟的',
  cute: '可愛的',
  water: '能感受水的',
  communal: '大家一起用的',
  floral: '花朵綻放的',
  colorful: '色彩繽紛的',
  luxurious: '豪華的',
  fire: '能感受火的',
  wooden: '木製的',
  hard: '堅硬的',
  training: '訓練用的',
  vehicle: '交通工具',
  wind: '能感受風的',
  tidy: '整潔的',
  healing: '能治癒傷口的',
  metallic: '金屬的',
  shiny: '閃亮亮的',
  gathered: '集聚在一起的',
  arcane: '艱深難懂的',
  text: '有文字的',
  stone: '石製的',
  slender: '細長的',
  earth: '能感受土的',
  ornamental: '觀賞用的',
  foodlike: '像食物的',
  mysterious: '奇妙的',
  noisy: '會發出聲響的',
  playground: '遊戲區',
  round: '圓滾滾的',
  fabric: '布製的',
  electric: '以電力驅動的',
  trash: '垃圾',
  wobbly: '會搖晃的',
  spinning: '會旋轉的',
  ocean: '能感受海的',
  square: '方方的',
  container: '容器',
  eerie: '詭異的',
  pointy: '尖尖的',
  glass: '有玻璃的',
  construction: '建設',
  symbolic: '象徵',
}
